Propagate reverts from external contract calls.

Before this fix the following code to `should_revert()` or `should_revert2()`
would succeed even though it clearly should not.

```
contract A:
  contract_b: B
  pub fn __init__(contract_b: address):
    self.contract_b = B(contract_b)

  pub fn should_revert():
    self.contract_b.fail()

  pub fn should_revert2():
    self.contract_b.fail_with_custom_error()

struct SomeError:
  pass

contract B:

  pub fn fail():
    revert

  pub fn fail_with_custom_error():
    revert SomeError()
```

With this fix the revert errors are properly passed upwards the call hierachy.
